---
- name: "Receive events from ACI Nexus Dashboard"
  hosts: "localhost"
  # Source PanOS config
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 9000
    - ansible.eda.kafka:
        host: kafka
        port: 9092
        topic: kafka-topic
        #group_id: ansible-eda        
  # Rule config logs
  rules:
    - name: "Handle Cisco ACI Compliance"
      condition: event.payload.type == "CONFIG"
      actions:
        - print_event:
            pretty: true
        # Config compliance
        - run_job_template:
            organization: "Default"
            name: "AWS EDA Cisco ACI: Compliance"
